name: JobFlow
options:
  bundleIdPrefix: com.jobflow
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: en
  xcodeVersion: "15.0"
  
configs:
  Debug: debug
  Release: release

configFiles:
  Debug: Config.xcconfig
  Release: Config.xcconfig

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift.git
    from: 2.0.0

targets:
  JobFlow:
    type: application
    platform: iOS
    sources:
      - path: JobFlow
        name: JobFlow
        type: group
    info:
      path: JobFlow/Resources/Info.plist
      properties:
        CFBundleDisplayName: JobFlow
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: ""
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    dependencies:
      - package: Supabase
        product: Supabase
    settings:
      base:
        PRODUCT_NAME: JobFlow
        PRODUCT_BUNDLE_IDENTIFIER: com.jobflow.JobFlow
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.9"
        ENABLE_PREVIEWS: true
        INFOPLIST_FILE: JobFlow/Resources/Info.plist
        DEVELOPMENT_ASSET_PATHS: ""
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: "5YA5U25PAV"
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        GENERATE_INFOPLIST_FILE: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
        SUPABASE_URL: $(SUPABASE_URL)
        SUPABASE_ANON_KEY: $(SUPABASE_ANON_KEY)


